spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gradation
    username: root
<<<<<<< HEAD
<<<<<<< HEAD
    password : 8794
=======
    password : 123
>>>>>>> f24b753e4fe35d50ec127bc65dcdfd6e210f78ee
=======
    password : 8794
>>>>>>> 285aa4bf80f1eedd567f925b0f1320c3c0033fd2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      port: 6379
      host: localhost
  mail:
    host: smtp.gmail.com
    port: 587
    username: gd122572@gmail.com
    password: fzbujhthgsrmwhwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your_jwt_secret_key
  access-token:
    expiration: 360000000 # 1 hour in milliseconds
  refresh-token:
    expiration: 604800000 # 1 week in milliseconds

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

openvidu:
  url: ${OPENVIDU_URL:http://localhost:4443/}
  secret: ${OPENVIDU_SECRET:MY_SECRET}
