spring:
  datasource:
    url: jdbc:mysql://theramzee-mysql-1:3306/gradation_db
    username: root
    password : root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      port: 6379
      host: theramzee_theramzee-network
  mail:
    host: smtp.gmail.com
    port: 587
    username: gd122572@gmail.com
    password: fzbujhthgsrmwhwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your_jwt_secret_key
  access-token:
    expiration: 360000000 # 1 hour in milliseconds
  refresh-token:
    expiration: 604800000 # 1 week in milliseconds

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

openvidu:
  url: ${OPENVIDU_URL:https://ramzee.online:8443/}
  secret: ${OPENVIDU_SECRET:dleogus1}
