version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gradation_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build: ./backend
    image: ${DOCKER_IMAGE_PREFIX}-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gradation_db
      SPRING_REDIS_HOST: redis
    restart: unless-stopped

  frontended:
    build: ./frontended
    image: ${DOCKER_IMAGE_PREFIX}-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build: ./nginx
    image: ${DOCKER_IMAGE_PREFIX}-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontended
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
