services:
  backend:
    build: ./backend
    image: ${BACKEND_IMAGE}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - theramzee-network

  frontend:
    build: ./frontend
    image: ${FRONTEND_IMAGE}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - theramzee-network

networks:
  theramzee-network:
    external: true