services:
  nginx:
    build: ./nginx
    image: ${NGINX_IMAGE}
    container_name: theramzee-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    networks:
      - theramzee-network

networks:
  theramzee-network:
    external: true