services:
  mysql:
    image: mysql:8.0.37  # 2025년 기준 LTS 버전
    container_name: theramzee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    networks:
      - theramzee-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u${MYSQL_USERNAME}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine  # 경량화 버전
    container_name: theramzee-redis
    command: redis-server --bind 0.0.0.0
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - theramzee-redis-data:/data
    restart: unless-stopped
    networks:
      - theramzee-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./backend
    image: ${BACKEND_IMAGE}
    container_name: theramzee-backend
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - theramzee-network

  frontend:
    build: ./frontend
    image: ${FRONTEND_IMAGE}
    container_name: theramzee-frontend
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - theramzee-network

  nginx:
    build: ./nginx
    image: ${NGINX_IMAGE}
    container_name: theramzee-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_files:${STATIC_FILES_PATH}
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - theramzee-network

volumes:
  theramzee-mysql-data:
  theramzee-redis-data:
  static_files:

networks:
  theramzee-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24  # 고정 IP 대역